import type { BeastCraftCategory, BeastCraftRecipe, BeastInfo } from './types';

export const DEFAULT_YELLOW_BEAST_PRICE = 15;

export const BESTIARY_CATEGORIES: Array<{ id: BeastCraftCategory | 'all'; label: string }> = [
  { id: 'all', label: '全部配方' },
  { id: 'imprint_split', label: '拓印/分裂' },
  { id: 'modifier_manipulation', label: '救詞/前置後綴' },
  { id: 'corruption_quality', label: '30%品質瓦爾' },
  { id: 'unique_item', label: '傳奇/頭目' },
];

export const RED_BEASTS: BeastInfo[] = [
  {
    id: 'craicic_chimeral',
    nameZh: '深海奇美拉',
    nameEn: 'Craicic Chimeral',
    family: 'The Deep',
    genus: 'Craicic',
    minLevel: 68,
    defaultMarketChaos: 280,
    rarity: 'Red',
  },
  {
    id: 'fenumal_plagued_arachnid',
    nameZh: '芬斯羅斯疫病蛛',
    nameEn: 'Fenumal Plagued Arachnid',
    family: 'The Caverns',
    genus: 'Fenumal',
    minLevel: 68,
    defaultMarketChaos: 210,
    rarity: 'Red',
  },
  {
    id: 'farric_frost_crawford',
    nameZh: '法拉爾霜爪蟹',
    nameEn: 'Farric Frost Crawford',
    family: 'The Wilds',
    genus: 'Farric',
    minLevel: 68,
    defaultMarketChaos: 95,
    rarity: 'Red',
  },
  {
    id: 'farric_lynx_alpha',
    nameZh: '法拉爾首領猞猁',
    nameEn: 'Farric Lynx Alpha',
    family: 'The Wilds',
    genus: 'Farric',
    minLevel: 68,
    defaultMarketChaos: 90,
    rarity: 'Red',
  },
  {
    id: 'craicic_vassal',
    nameZh: '深海封臣',
    nameEn: 'Craicic Vassal',
    family: 'The Deep',
    genus: 'Craicic',
    minLevel: 68,
    defaultMarketChaos: 65,
    rarity: 'Red',
  },
  {
    id: 'saqawine_vulture',
    nameZh: '薩恩禿鷹',
    nameEn: 'Saqawine Vulture',
    family: 'The Sands',
    genus: 'Saqawine',
    minLevel: 68,
    defaultMarketChaos: 120,
    rarity: 'Red',
  },
  {
    id: 'farric_tiger_alpha',
    nameZh: '法拉爾首領虎',
    nameEn: 'Farric Tiger Alpha',
    family: 'The Wilds',
    genus: 'Farric',
    minLevel: 75,
    defaultMarketChaos: 160,
    rarity: 'Red',
  },
  {
    id: 'saqawine_retch',
    nameZh: '薩恩嘔吐者',
    nameEn: 'Saqawine Retch',
    family: 'The Sands',
    genus: 'Saqawine',
    minLevel: 68,
    defaultMarketChaos: 45,
    rarity: 'Red',
  },
];

export const BESTIARY_RECIPES: BeastCraftRecipe[] = [
  {
    id: 'imprint_magic',
    nameZh: '拓印魔法物品',
    nameEn: 'Create an Imprint of a Magic Item',
    category: 'imprint_split',
    primaryBeastId: 'craicic_chimeral',
    primaryBeastNameZh: '深海奇美拉',
    primaryBeastNameEn: 'Craicic Chimeral',
    yellowBeastCount: 3,
    outputDescriptionZh: '產出一顆拓印寶珠，可將該魔法物品還原至當前詞綴狀態',
    defaultEstimatedOutputChaos: 420,
  },
  {
    id: 'split_item',
    nameZh: '分裂稀有物品',
    nameEn: 'Split an Item into Two',
    category: 'imprint_split',
    primaryBeastId: 'fenumal_plagued_arachnid',
    primaryBeastNameZh: '芬斯羅斯疫病蛛',
    primaryBeastNameEn: 'Fenumal Plagued Arachnid',
    yellowBeastCount: 3,
    outputDescriptionZh: '將未分裂之物品隨機拆分為兩件各自繼承一半詞綴的複製品',
    defaultEstimatedOutputChaos: 320,
  },
  {
    id: 'add_prefix_remove_suffix',
    nameZh: '新增前綴，移除隨機後綴',
    nameEn: 'Add a Prefix, Remove a Random Suffix',
    category: 'modifier_manipulation',
    primaryBeastId: 'farric_frost_crawford',
    primaryBeastNameZh: '法拉爾霜爪蟹',
    primaryBeastNameEn: 'Farric Frost Crawford',
    yellowBeastCount: 3,
    outputDescriptionZh: '保證新增一條前綴，並安全隨機剝離一條後綴（救詞救裝必備）',
    defaultEstimatedOutputChaos: 150,
  },
  {
    id: 'add_suffix_remove_prefix',
    nameZh: '新增後綴，移除隨機前綴',
    nameEn: 'Add a Suffix, Remove a Random Prefix',
    category: 'modifier_manipulation',
    primaryBeastId: 'farric_lynx_alpha',
    primaryBeastNameZh: '法拉爾首領猞猁',
    primaryBeastNameEn: 'Farric Lynx Alpha',
    yellowBeastCount: 3,
    outputDescriptionZh: '保證新增一條後綴，並安全隨機剝離一條前綴',
    defaultEstimatedOutputChaos: 145,
  },
  {
    id: 'corrupt_30_quality',
    nameZh: '腐化物品至 30% 品質',
    nameEn: 'Corrupt an Item with 30% Quality',
    category: 'corruption_quality',
    primaryBeastId: 'craicic_vassal',
    primaryBeastNameZh: '深海封臣',
    primaryBeastNameEn: 'Craicic Vassal',
    yellowBeastCount: 3,
    outputDescriptionZh: '直接將武器或防具提升至 30% 品質並賦予已污染狀態',
    defaultEstimatedOutputChaos: 110,
  },
  {
    id: 'reroll_unique_keystone',
    nameZh: '重擲隨機傳奇物品數值',
    nameEn: 'Reroll Values of Unique Item',
    category: 'unique_item',
    primaryBeastId: 'saqawine_vulture',
    primaryBeastNameZh: '薩恩禿鷹',
    primaryBeastNameEn: 'Saqawine Vulture',
    yellowBeastCount: 3,
    outputDescriptionZh: '重新骰擲傳奇裝備的所有詞綴卷值，追尋頂卷高價值數值',
    defaultEstimatedOutputChaos: 180,
  },
  {
    id: 'open_farrul_portal',
    nameZh: '開啟法拉爾密林巢穴傳送門',
    nameEn: "Open a Portal to Farrul's Den",
    category: 'unique_item',
    primaryBeastId: 'farric_tiger_alpha',
    primaryBeastNameZh: '法拉爾首領虎',
    primaryBeastNameEn: 'Farric Tiger Alpha',
    yellowBeastCount: 3,
    outputDescriptionZh: '開啟頭目傳送門，挑戰法拉爾以獲取法拉爾貓衣與附魔',
    defaultEstimatedOutputChaos: 220,
  },
];
