import type { CraftMod } from './types';

export const PREFIX_MODS: CraftMod[] = [
  {
    id: 'maximum_life',
    name: 'Maximum Life',
    nameZh: '最大生命',
    group: 'Life',
    type: 'prefix',
    tags: ['life'],
    applicableClasses: ['body_armour', 'helmet', 'gloves', 'boots', 'shield', 'ring', 'amulet', 'belt'],
    tiers: [
      { tier: 1, ilvl: 86, weight: 1000, statText: '+120 to 129 to Maximum Life', statTextZh: '+120~129 最大生命', minValue: 120, maxValue: 129 },
      { tier: 2, ilvl: 73, weight: 1000, statText: '+110 to 119 to Maximum Life', statTextZh: '+110~119 最大生命', minValue: 110, maxValue: 119 },
      { tier: 3, ilvl: 64, weight: 1000, statText: '+100 to 109 to Maximum Life', statTextZh: '+100~109 最大生命', minValue: 100, maxValue: 109 },
    ],
  },
  {
    id: 'movement_speed',
    name: 'Movement Speed',
    nameZh: '增加移動速度',
    group: 'MovementVelocity',
    type: 'prefix',
    tags: ['speed'],
    applicableClasses: ['boots'],
    tiers: [
      { tier: 1, ilvl: 86, weight: 500, statText: '35% increased Movement Speed', statTextZh: '35% 增加移動速度', minValue: 35, maxValue: 35 },
      { tier: 2, ilvl: 55, weight: 1000, statText: '30% increased Movement Speed', statTextZh: '30% 增加移動速度', minValue: 30, maxValue: 30 },
      { tier: 3, ilvl: 32, weight: 1000, statText: '25% increased Movement Speed', statTextZh: '25% 增加移動速度', minValue: 25, maxValue: 25 },
    ],
  },
  {
    id: 'increased_physical_damage',
    name: '% Increased Physical Damage',
    nameZh: '增加物理傷害 %',
    group: 'IncreasedPhysicalDamage',
    type: 'prefix',
    tags: ['physical', 'attack'],
    applicableClasses: ['weapon_2h_bow', 'weapon_1h'],
    tiers: [
      { tier: 1, ilvl: 83, weight: 250, statText: '170% to 179% increased Physical Damage', statTextZh: '170%~179% 增加物理傷害', minValue: 170, maxValue: 179 },
      { tier: 2, ilvl: 73, weight: 500, statText: '150% to 169% increased Physical Damage', statTextZh: '150%~169% 增加物理傷害', minValue: 150, maxValue: 169 },
      { tier: 3, ilvl: 60, weight: 750, statText: '135% to 149% increased Physical Damage', statTextZh: '135%~149% 增加物理傷害', minValue: 135, maxValue: 149 },
    ],
  },
  {
    id: 'flat_physical_damage',
    name: 'Adds Physical Damage',
    nameZh: '附加物理傷害',
    group: 'FlatPhysicalDamage',
    type: 'prefix',
    tags: ['physical', 'attack'],
    applicableClasses: ['weapon_2h_bow', 'weapon_1h', 'ring', 'amulet'],
    tiers: [
      { tier: 1, ilvl: 77, weight: 500, statText: 'Adds 19 to 38 Physical Damage', statTextZh: '附加 19~38 物理傷害', minValue: 19, maxValue: 38 },
      { tier: 2, ilvl: 65, weight: 750, statText: 'Adds 15 to 30 Physical Damage', statTextZh: '附加 15~30 物理傷害', minValue: 15, maxValue: 30 },
      { tier: 3, ilvl: 50, weight: 1000, statText: 'Adds 11 to 23 Physical Damage', statTextZh: '附加 11~23 物理傷害', minValue: 11, maxValue: 23 },
    ],
  },
  {
    id: 'increased_spell_damage',
    name: '% Increased Spell Damage',
    nameZh: '增加法術傷害 %',
    group: 'SpellDamage',
    type: 'prefix',
    tags: ['caster'],
    applicableClasses: ['weapon_1h', 'shield', 'amulet'],
    tiers: [
      { tier: 1, ilvl: 84, weight: 400, statText: '100% to 109% increased Spell Damage', statTextZh: '100%~109% 增加法術傷害', minValue: 100, maxValue: 109 },
      { tier: 2, ilvl: 72, weight: 600, statText: '90% to 99% increased Spell Damage', statTextZh: '90%~99% 增加法術傷害', minValue: 90, maxValue: 99 },
      { tier: 3, ilvl: 60, weight: 800, statText: '80% to 89% increased Spell Damage', statTextZh: '80%~89% 增加法術傷害', minValue: 80, maxValue: 89 },
    ],
  },
  {
    id: 'all_spell_gems_level',
    name: '+1 to Level of all Spell Skill Gems',
    nameZh: '+1 所有法術技能寶石等級',
    group: 'AllSpellSkillGems',
    type: 'prefix',
    tags: ['caster', 'gem'],
    applicableClasses: ['weapon_1h', 'amulet'],
    tiers: [
      { tier: 1, ilvl: 82, weight: 50, statText: '+1 to Level of all Spell Skill Gems', statTextZh: '+1 所有法術技能寶石等級', minValue: 1, maxValue: 1 },
    ],
  },
  {
    id: 'increased_defences',
    name: '% Increased Local Defences',
    nameZh: '增加防禦 (護甲/閃避/能量護盾) %',
    group: 'IncreasedDefences',
    type: 'prefix',
    tags: ['defences'],
    applicableClasses: ['body_armour', 'helmet', 'gloves', 'boots', 'shield'],
    tiers: [
      { tier: 1, ilvl: 86, weight: 600, statText: '101% to 110% increased Local Defences', statTextZh: '101%~110% 增加防禦', minValue: 101, maxValue: 110 },
      { tier: 2, ilvl: 72, weight: 800, statText: '91% to 100% increased Local Defences', statTextZh: '91%~100% 增加防禦', minValue: 91, maxValue: 100 },
      { tier: 3, ilvl: 55, weight: 1000, statText: '75% to 90% increased Local Defences', statTextZh: '75%~90% 增加防禦', minValue: 75, maxValue: 90 },
    ],
  },
  {
    id: 'flat_defences',
    name: 'Flat Local Defences',
    nameZh: '附加防禦值 (護甲/閃避/護盾)',
    group: 'FlatDefences',
    type: 'prefix',
    tags: ['defences'],
    applicableClasses: ['body_armour', 'helmet', 'gloves', 'boots', 'shield'],
    tiers: [
      { tier: 1, ilvl: 86, weight: 600, statText: '+136 to 145 to Local Defences', statTextZh: '+136~145 防禦點數', minValue: 136, maxValue: 145 },
      { tier: 2, ilvl: 75, weight: 800, statText: '+121 to 135 to Local Defences', statTextZh: '+121~135 防禦點數', minValue: 121, maxValue: 135 },
      { tier: 3, ilvl: 60, weight: 1000, statText: '+105 to 120 to Local Defences', statTextZh: '+105~120 防禦點數', minValue: 105, maxValue: 120 },
    ],
  },
  {
    id: 'minion_damage',
    name: '% Increased Minion Damage',
    nameZh: '召喚物增加傷害 %',
    group: 'MinionDamage',
    type: 'prefix',
    tags: ['minion'],
    applicableClasses: ['weapon_1h', 'helmet'],
    tiers: [
      { tier: 1, ilvl: 84, weight: 500, statText: 'Minions deal 75% to 84% increased Damage', statTextZh: '召喚物造成 75%~84% 增加傷害', minValue: 75, maxValue: 84 },
      { tier: 2, ilvl: 73, weight: 750, statText: 'Minions deal 65% to 74% increased Damage', statTextZh: '召喚物造成 65%~74% 增加傷害', minValue: 65, maxValue: 74 },
    ],
  },
];
