import type { CraftMod } from './types';

export const SUFFIX_MODS: CraftMod[] = [
  {
    id: 'fire_resistance',
    name: 'Fire Resistance',
    nameZh: '火焰抗性',
    group: 'FireResistance',
    type: 'suffix',
    tags: ['elemental', 'fire', 'resistance'],
    applicableClasses: ['body_armour', 'helmet', 'gloves', 'boots', 'shield', 'ring', 'amulet', 'belt'],
    tiers: [
      { tier: 1, ilvl: 84, weight: 1000, statText: '+46% to 48% to Fire Resistance', statTextZh: '+46%~48% 火焰抗性', minValue: 46, maxValue: 48 },
      { tier: 2, ilvl: 72, weight: 1000, statText: '+42% to 45% to Fire Resistance', statTextZh: '+42%~45% 火焰抗性', minValue: 42, maxValue: 45 },
      { tier: 3, ilvl: 60, weight: 1000, statText: '+36% to 41% to Fire Resistance', statTextZh: '+36%~41% 火焰抗性', minValue: 36, maxValue: 41 },
    ],
  },
  {
    id: 'cold_resistance',
    name: 'Cold Resistance',
    nameZh: '冰冷抗性',
    group: 'ColdResistance',
    type: 'suffix',
    tags: ['elemental', 'cold', 'resistance'],
    applicableClasses: ['body_armour', 'helmet', 'gloves', 'boots', 'shield', 'ring', 'amulet', 'belt'],
    tiers: [
      { tier: 1, ilvl: 84, weight: 1000, statText: '+46% to 48% to Cold Resistance', statTextZh: '+46%~48% 冰冷抗性', minValue: 46, maxValue: 48 },
      { tier: 2, ilvl: 72, weight: 1000, statText: '+42% to 45% to Cold Resistance', statTextZh: '+42%~45% 冰冷抗性', minValue: 42, maxValue: 45 },
      { tier: 3, ilvl: 60, weight: 1000, statText: '+36% to 41% to Cold Resistance', statTextZh: '+36%~41% 冰冷抗性', minValue: 36, maxValue: 41 },
    ],
  },
  {
    id: 'lightning_resistance',
    name: 'Lightning Resistance',
    nameZh: '閃電抗性',
    group: 'LightningResistance',
    type: 'suffix',
    tags: ['elemental', 'lightning', 'resistance'],
    applicableClasses: ['body_armour', 'helmet', 'gloves', 'boots', 'shield', 'ring', 'amulet', 'belt'],
    tiers: [
      { tier: 1, ilvl: 84, weight: 1000, statText: '+46% to 48% to Lightning Resistance', statTextZh: '+46%~48% 閃電抗性', minValue: 46, maxValue: 48 },
      { tier: 2, ilvl: 72, weight: 1000, statText: '+42% to 45% to Lightning Resistance', statTextZh: '+42%~45% 閃電抗性', minValue: 42, maxValue: 45 },
      { tier: 3, ilvl: 60, weight: 1000, statText: '+36% to 41% to Lightning Resistance', statTextZh: '+36%~41% 閃電抗性', minValue: 36, maxValue: 41 },
    ],
  },
  {
    id: 'chaos_resistance',
    name: 'Chaos Resistance',
    nameZh: '混沌抗性',
    group: 'ChaosResistance',
    type: 'suffix',
    tags: ['chaos', 'resistance'],
    applicableClasses: ['body_armour', 'helmet', 'gloves', 'boots', 'shield', 'ring', 'amulet', 'belt'],
    tiers: [
      { tier: 1, ilvl: 81, weight: 500, statText: '+31% to 35% to Chaos Resistance', statTextZh: '+31%~35% 混沌抗性', minValue: 31, maxValue: 35 },
      { tier: 2, ilvl: 65, weight: 750, statText: '+26% to 30% to Chaos Resistance', statTextZh: '+26%~30% 混沌抗性', minValue: 26, maxValue: 30 },
      { tier: 3, ilvl: 50, weight: 1000, statText: '+21% to 25% to Chaos Resistance', statTextZh: '+21%~25% 混沌抗性', minValue: 21, maxValue: 25 },
    ],
  },
  {
    id: 'spell_suppression',
    name: 'Chance to Suppress Spell Damage',
    nameZh: '法術傷害壓抑率 %',
    group: 'SpellSuppression',
    type: 'suffix',
    tags: ['defences'],
    requiresAttribute: 'dex',
    applicableClasses: ['body_armour', 'helmet', 'gloves', 'boots', 'shield'],
    tiers: [
      { tier: 1, ilvl: 86, weight: 500, statText: '+20% to 22% Chance to Suppress Spell Damage', statTextZh: '+20%~22% 法術傷害壓抑率', minValue: 20, maxValue: 22 },
      { tier: 2, ilvl: 75, weight: 750, statText: '+17% to 19% Chance to Suppress Spell Damage', statTextZh: '+17%~19% 法術傷害壓抑率', minValue: 17, maxValue: 19 },
      { tier: 3, ilvl: 60, weight: 1000, statText: '+13% to 16% Chance to Suppress Spell Damage', statTextZh: '+13%~16% 法術傷害壓抑率', minValue: 13, maxValue: 16 },
    ],
  },
  {
    id: 'attack_speed',
    name: '% Increased Attack Speed',
    nameZh: '增加攻擊速度 %',
    group: 'AttackSpeed',
    type: 'suffix',
    tags: ['attack', 'speed'],
    applicableClasses: ['weapon_2h_bow', 'weapon_1h', 'gloves'],
    tiers: [
      { tier: 1, ilvl: 84, weight: 600, statText: '16% to 19% increased Attack Speed', statTextZh: '16%~19% 增加攻擊速度', minValue: 16, maxValue: 19 },
      { tier: 2, ilvl: 70, weight: 800, statText: '14% to 15% increased Attack Speed', statTextZh: '14%~15% 增加攻擊速度', minValue: 14, maxValue: 15 },
      { tier: 3, ilvl: 55, weight: 1000, statText: '11% to 13% increased Attack Speed', statTextZh: '11%~13% 增加攻擊速度', minValue: 11, maxValue: 13 },
    ],
  },
  {
    id: 'cast_speed',
    name: '% Increased Cast Speed',
    nameZh: '增加施法速度 %',
    group: 'CastSpeed',
    type: 'suffix',
    tags: ['caster', 'speed'],
    applicableClasses: ['weapon_1h', 'ring', 'amulet'],
    tiers: [
      { tier: 1, ilvl: 83, weight: 600, statText: '17% to 19% increased Cast Speed', statTextZh: '17%~19% 增加施法速度', minValue: 17, maxValue: 19 },
      { tier: 2, ilvl: 72, weight: 800, statText: '14% to 16% increased Cast Speed', statTextZh: '14%~16% 增加施法速度', minValue: 14, maxValue: 16 },
    ],
  },
  {
    id: 'critical_multiplier',
    name: 'Global Critical Strike Multiplier',
    nameZh: '全域暴擊加成 %',
    group: 'CriticalMultiplier',
    type: 'suffix',
    tags: ['critical'],
    applicableClasses: ['weapon_2h_bow', 'weapon_1h', 'amulet', 'ring'],
    tiers: [
      { tier: 1, ilvl: 84, weight: 400, statText: '+35% to 38% to Global Critical Strike Multiplier', statTextZh: '+35%~38% 全域暴擊加成', minValue: 35, maxValue: 38 },
      { tier: 2, ilvl: 73, weight: 600, statText: '+30% to 34% to Global Critical Strike Multiplier', statTextZh: '+30%~34% 全域暴擊加成', minValue: 30, maxValue: 34 },
    ],
  },
  {
    id: 'strength',
    name: '+ to Strength',
    nameZh: '附加力量',
    group: 'Strength',
    type: 'suffix',
    tags: ['attribute'],
    applicableClasses: ['body_armour', 'helmet', 'gloves', 'boots', 'shield', 'ring', 'amulet', 'belt'],
    tiers: [
      { tier: 1, ilvl: 82, weight: 1000, statText: '+51 to 55 to Strength', statTextZh: '+51~55 力量', minValue: 51, maxValue: 55 },
      { tier: 2, ilvl: 74, weight: 1000, statText: '+43 to 50 to Strength', statTextZh: '+43~50 力量', minValue: 43, maxValue: 50 },
    ],
  },
];
