import type { FactionType, LogbookRemnant } from './types';

export const EXPEDITION_FACTIONS: Array<{ id: FactionType; nameZh: string; npcZh: string; baseEvChaos: number }> = [
  { id: 'black_scythe', nameZh: '黑鐮傭兵', npcZh: '圖貞 (Tujen)', baseEvChaos: 120 },
  { id: 'sun', nameZh: '烈日聖騎士', npcZh: '丹尼格 (Dannig)', baseEvChaos: 140 },
  { id: 'order', nameZh: '秩序之杯', npcZh: '羅格 (Rog)', baseEvChaos: 90 },
  { id: 'chalice', nameZh: '破碎聖杯', npcZh: '格溫寧 (Gwennen)', baseEvChaos: 70 },
];

export const EXPEDITION_REMNANTS: LogbookRemnant[] = [
  {
    id: 'duplicated_runic',
    nameZh: '符文怪物複製',
    nameEn: 'Runic Monsters are Duplicated',
    type: 'reward',
    logbookDropMultiplier: 1.0,
    runicMonsterMultiplier: 2.0,
    isDeadly: false,
    descriptionZh: '所有符文怪物生成數量加倍，極大提升文物與日誌掉落數量',
  },
  {
    id: 'logbook_quantity',
    nameZh: '怪物掉落探險日誌 +50%',
    nameEn: '50% increased Logbooks dropped by Monsters',
    type: 'reward',
    logbookDropMultiplier: 1.5,
    runicMonsterMultiplier: 1.0,
    isDeadly: false,
    descriptionZh: '日誌連鎖產出核心詞綴，確保日誌永動滾雪球收益',
  },
  {
    id: 'runic_item_quantity',
    nameZh: '符文怪掉落數量 +40%',
    nameEn: '40% increased Quantity of Items dropped by Runic Monsters',
    type: 'quantity',
    logbookDropMultiplier: 1.2,
    runicMonsterMultiplier: 1.4,
    isDeadly: false,
    descriptionZh: '提升符文怪物的整體掉落數量乘數',
  },
  {
    id: 'immune_ele',
    nameZh: '怪物免疫所有元素傷害',
    nameEn: 'Monsters are Immune to Elemental Damage',
    type: 'danger',
    logbookDropMultiplier: 1.0,
    runicMonsterMultiplier: 1.0,
    isDeadly: true,
    descriptionZh: '元素流派完全無法破防造成傷害，極度致命！',
  },
  {
    id: 'immune_chaos',
    nameZh: '怪物免疫混沌傷害',
    nameEn: 'Monsters are Immune to Chaos Damage',
    type: 'danger',
    logbookDropMultiplier: 1.0,
    runicMonsterMultiplier: 1.0,
    isDeadly: true,
    descriptionZh: '混沌、中毒與毒雨流派完全無法造成傷害，極度致命！',
  },
  {
    id: 'immune_phys',
    nameZh: '怪物免疫物理傷害',
    nameEn: 'Monsters are Immune to Physical Damage',
    type: 'danger',
    logbookDropMultiplier: 1.0,
    runicMonsterMultiplier: 1.0,
    isDeadly: true,
    descriptionZh: '純物理攻擊與流血流派無法造成傷害，極度致命！',
  },
  {
    id: 'monster_crit',
    nameZh: '怪物暴擊率提高且暴擊加成 +45%',
    nameEn: 'Monsters have increased Critical Strike Chance & Multiplier',
    type: 'danger',
    logbookDropMultiplier: 1.0,
    runicMonsterMultiplier: 1.0,
    isDeadly: true,
    descriptionZh: '怪物極易一擊必殺玩家，高威脅致命詞綴',
  },
  {
    id: 'excavated_radius',
    nameZh: '炸藥引爆半徑擴大 25%',
    nameEn: '25% increased Explosive Placement Range',
    type: 'quantity',
    logbookDropMultiplier: 1.1,
    runicMonsterMultiplier: 1.2,
    isDeadly: false,
    descriptionZh: '更容易串聯更多符文標柱與地下寶箱節點',
  },
];
